# =====================================================================================================
#   Uncomment the database you want to use and comment the others
#   the port and database name should be the same as the one you created in your local database server
#   dont forget to change the username and password if you are not using the default ones
# =====================================================================================================

# db.driver=org.postgresql.Driver
db.driver=com.mysql.cj.jdbc.Driver
# db.driver=org.mariadb.jdbc.Driver

# db.url=jdbc:postgresql://localhost:5432/cofre_db
db.url=jdbc:mysql://localhost:3306/cofre_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
# db.url=jdbc:mariadb://localhost:3306/cofre_db


# If you want to use PostgreSQL default username and password, use : postgres/postgres
db.user=root
db.password=root